name: Playwright Tests

on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  pull_request:
    branches:
      - main  # Run tests on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for the CI job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Set the Node.js version, update if necessary

    - name: Install dependencies
      run: |
        npm install  # Install all dependencies defined in package.json

    - name: Run Playwright tests
      run: |
        npx playwright install  # Install browsers for Playwright
        npm run test:formValidation  # Run the form validation tests

    - name: Upload Playwright test results
      uses: actions/upload-artifact@v3  # Use stable v3 version
      with:
        name: playwright-report
        path: playwright-report  # Upload Playwright's test reports if needed
