name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Run Playwright tests
      run: |
        npx playwright install
        npm run test:formValidation

    - name: Upload Playwright test results
      uses: actions/upload-artifact@v2.2.4  # Specific version of the action
      with:
        name: playwright-report
        path: playwright-report
