name: Playwright Tests  # Defines the name of the GitHub Actions workflow

on:
  push:
    branches:
      - main  # Triggers workflow when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Triggers workflow on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Specifies the runner environment (latest Ubuntu)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Clones the repository into the runner

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Installs Node.js environment
        with:
          node-version: '16'  # Specifies Node.js version

      - name: Install required libraries
        run: |
          sudo apt-get update  # Updates package lists
          sudo apt-get install -y \  # Installs system dependencies needed for browsers
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3 \
            libgdk-pixbuf2.0-0 \
            libnspr4 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            xdg-utils \
            libvpx-dev \
            libgstreamer1.0-0 \
            libgstreamer-plugins-base1.0-0 \
            libopus0 \
            libegl1 \
            libpci3 \
            libdbus-glib-1-2

      - name: Install Playwright
        run: npm ci  # Installs project dependencies from package-lock.json

      - name: Install Playwright Browsers (Chromium and Firefox only)
        run: npx playwright install chromium firefox  # Downloads required browsers

      - name: Run tests on both Firefox and Chromium in parallel
        run: |
          npx playwright test --project=firefox tests/formValidation.spec.ts &  # Runs tests in Firefox
          npx playwright test --project=chromium tests/formValidation.spec.ts &  # Runs tests in Chromium
          wait  # Ensures both test processes complete

      - name: Generate Playwright Test Report
        run: |
          npx playwright test --project=firefox --reporter=html  # Generates HTML report for Firefox
          npx playwright test --project=chromium --reporter=html  # Generates HTML report for Chromium
          echo "Test report generated successfully"

      - name: Upload Playwright Test Report
        uses: actions/upload-artifact@v4  # Uploads the test report as an artifact
        with:
          name: playwright-report  # Name of the uploaded artifact
          path: playwright-report/  # Path where reports are stored
