name: Playwright Tests

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run Playwright Tests
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for GitHub Actions

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.17.0  # Ensure your project's Node.js version matches this

    # Install dependencies
    - name: Install dependencies
      run: npm install

    - name: Install dependencies for Playwright
      run: |
        npx playwright install-deps

    # Install Playwright Browsers
    - name: Install Playwright Browsers
      run: npx playwright install

    # Run Playwright tests
    - name: Run Playwright Tests
      run: npx playwright test

    # Upload Playwright test report (optional)
    - name: Upload Playwright Report
      if: always()  # Run this step even if the tests fail
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report  # Playwright stores test reports here by default.
