name: Playwright Tests

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run Playwright Tests
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for GitHub Actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.17.0

    - name: Install system dependencies (Fix missing packages)
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2t64 libffi-dev libx264-dev

    - name: Install dependencies
      run: npm install

    - name: Install Playwright dependencies
      run: npx playwright install-deps

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Run Playwright Tests
      run: npx playwright test

    - name: Upload Playwright Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report
