name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install required libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libasound2 \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libcups2 \
          libdbus-1-3 \
          libgdk-pixbuf2.0-0 \
          libnspr4 \
          libnss3 \
          libx11-xcb1 \
          libxcomposite1 \
  
