name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Playwright dependencies
      run: |
        sudo npx playwright install-deps

    - name: Install Playwright
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install chromium firefox webkit

    - name: Run tests on all browsers in parallel
      run: |
        npx playwright test --project=firefox tests/formValidation.spec.ts --reporter=html --output=playwright-report-firefox &
        npx playwright test --project=chromium tests/formValidation.spec.ts --reporter=html --output=playwright-report-chromium &
        npx playwright test --project=webkit tests/formValidation.spec.ts --reporter=html --output=playwright-report-webkit &
        wait

    - name: Upload Playwright Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-firefox
        path: playwright-report-firefox/

    - name: Upload Playwright Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-chromium
        path: playwright-report-chromium/

    - name: Upload Playwright Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-webkit
        path: playwright-report-webkit/
