# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run Playwright Tests
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for GitHub Actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.17.0

    - name: Install system dependencies (Fix missing packages)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libasound2t64 \
          libffi-dev \
          libx264-dev \
          libnss3 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libxcomposite1 \
          libxrandr2 \
          libgbm1 \
          libpango-1.0-0 \
          libpangocairo-1.0-0 \
          libgtk-3-0 \
          libdrm2 \
          libxdamage1 \
          libxkbcommon0 \
          libxshmfence1 \
          libglu1-mesa \
          woff2 \  # Replaces libwoff2-1-1
          libgles2-mesa-dev \
          libvpx-dev \
          libevent-dev \
          libopus-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-libav \
          libharfbuzz-icu0 \
          libsecret-1-0 \
          libhyphen0 \
          libmanette-0.2-0 \
          libflite1 

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Run Playwright Tests
      run: npx playwright test

    - name: Upload Playwright Report
      if: always()
      uses: actions/upload-artifact@v4
      wi
