name: Playwright Tests  # Name of the workflow

on:
  push:
    branches:
      - main  # Trigger workflow when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow for pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for execution

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Clone the repository to the runner machine

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Install Node.js
        with:
          node-version: '16'  # Specify the Node.js version to use

      - name: Install required libraries
        run: |
          sudo apt-get update  # Update package lists
          sudo apt-get install -y \  # Install dependencies required for Playwright browsers
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3 \
            libgdk-pixbuf2.0-0 \
            libnspr4 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            xdg-utils \
            libvpx-dev \
            libgstreamer1.0-0 \
            libgstreamer-plugins-base1.0-0 \
            libopus0 \
            libegl1 \
            libpci3 \
            libdbus-glib-1-2

      - name: Install Playwright
        run: npm ci  # Install project dependencies defined in package-lock.json

      - name: Install Playwright Browsers (Chromium and Firefox only)
        run: npx playwright install chromium firefox  # Install Chromium and Firefox for testing

      - name: Run tests on both Firefox and Chromium in parallel
        run: |
          npx playwright test --project=firefox tests/formValidation.spec.ts &  # Run tests in Firefox
          npx playwright test --project=chromium tests/formValidation.spec.ts &  # Run tests in Chromium
          wait  # Wait for both tests to complete

      - name: Generate Playwright Test Report
        run: |
          npx playwright test --project=firefox --reporter=html  # Generate test report for Firefox
          npx playwright test --project=chromium --reporter=html  # Generate test report for Chromium
          echo "Test report generated successfully"

      - name: Upload Playwright Test Report
        uses: actions/upload-artifact@v4  # Upload test reports as artifacts for later access
        with:
          name: playwright-report  # Name of the uploaded artifact
          path: playwright-report/  # Directory where reports are stored
