name: Playwright Tests # Defines the name of the GitHub Actions workflow

on:
  push:
    branches:
      - main      # Triggers workflow when code is pushed to the main branch
  pull_request:
    branches:
      - main   # Triggers workflow on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Specifies the runner environment (latest Ubuntu)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Clones the repository into the runner

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Installs Node.js environment
      with:
        node-version: '16'  # Specifies Node.js version

    - name: Install required libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libcups2 \
          libdbus-1-3 \
          libgdk-pixbuf2.0-0 \
          libnspr4 \
          libnss3 \
          libx11-xcb1 \
          libxcomposite1 \
          libxdamage1 \
          libxrandr2 \
          xdg-utils \
          libvpx-dev \
          libgstreamer1.0-0 \
          libgstreamer-plugins-base1.0-0 \
          libopus0 \
          libegl1 \
          libpci3 \
          libdbus-glib-1-2

    - name: Install Playwright
      run: npm ci   # Installs project dependencies from package-lock.json

    - name: Install Playwright Browsers (Chromium and Firefox)
      run: npx playwright install chromium firefox  # Downloads required browsers

    - name: Run tests on both Firefox and Chromium in parallel
      run: |
        npx playwright test --project=firefox tests/formValidation.spec.ts & 
        npx playwright test --project=chromium tests/formValidation.spec.ts & 
        wait

    - name: Create directories for reports
      run: |
        mkdir -p playwright-report-firefox
        mkdir -p playwright-report-chromium

    - name: Generate Playwright Test Report for Firefox
      run: |
        npx playwright test --project=firefox --reporter=html --output=playwright-report-firefox/
        echo "Firefox test report generated successfully"

    - name: Generate Playwright Test Report for Chromium
      run: |
        npx playwright test --project=chromium --reporter=html --output=playwright-report-chromium/
        echo "Chromium test report generated successfully"

    - name: Upload Playwright Test Report for Firefox
      uses: actions/upload-artifact@v4   # Uploads the test report as an artifact
      with:
        name: playwright-report-firefox    # Name of the uploaded artifact for Firefox
        path: playwright-report-firefox/   # Path where Firefox reports are stored

    - name: Upload Playwright Test Report for Chromium
      uses: actions/upload-artifact@v4   # Uploads the test report as an artifact
      with:
        name: playwright-report-chromium    # Name of the uploaded artifact for Chromium
        path: playwright-report-chromium/   # Path where Chromium reports are stored
