name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install required libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libcups2 \
          libdbus-1-3 \
          libgdk-pixbuf2.0-0 \
          libnspr4 \
          libnss3 \
          libx11-xcb1 \
          libxcomposite1 \
          libxdamage1 \
          libxrandr2 \
          xdg-utils \
          libvpx-dev \
          libgstreamer1.0-0 \
          libgstreamer-plugins-base1.0-0 \
          libopus0 \
          libegl1 \
          libpci3 \
          libdbus-glib-1-2

    - name: Install Playwright
      run: npm ci

    - name: Install Playwright Browsers (Chromium and Firefox)
      run: npx playwright install chromium firefox

    - name: Run tests on both Firefox and Chromium in parallel
      run: |
        npx playwright test --project=firefox --reporter=html --output=playwright-report-firefox &
        npx playwright test --project=chromium --reporter=html --output=playwright-report-chromium &
        wait

    - name: Upload Playwright Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-firefox
        path: playwright-report-firefox/

    - name: Upload Playwright Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-chromium
        path: playwright-report-chromium/
