name: Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0

      - name: Install Dependencies
        run: npm install

      - name: Install Missing Ubuntu Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libasound2 \
            libffi8 \
            libx264-164 \
            libnss3 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libgtk-3-0 \
            libpango-1.0-0 \
            libatk1.0-0 \
            libcups2 \
            libasound2-data

      - name: Install Playwright Dependencies
        run: npx playwright install-deps

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
